### ISSUE TITLE
Specify key-value pair to search by in /search from client

### ISSUE THREAD

**Issue by Marcus-Adair** [sci-ndp/scidx-api#113]
User should be able to specify a key (eg., owner_org or some field specified in 'extras') and a value to search by when using Search functionality. Datasets should only come up when the value they entered into the search_terms matches a specific key in 'extras' or else where (instead of just doing a general search across all metadata).

This will can allow users to find data they want easier.

**Comment by rbardaji** [comment]
Hi Marcus, thanks for this issue. I will move it to the pop repo, as we have decided to split this repository into two: one for the pop part and another for the streaming part.
